/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VolumeController */

#ifndef _Included_VolumeController
#define _Included_VolumeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VolumeController
 * Method:    muteOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_muteOn
  (JNIEnv *, jclass);

/*
 * Class:     VolumeController
 * Method:    muteOff
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_muteOff
  (JNIEnv *, jclass);

/*
 * Class:     VolumeController
 * Method:    increaseBy10Percentage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_increaseBy10Percentage
  (JNIEnv *, jclass);

/*
 * Class:     VolumeController
 * Method:    decreaseBy10Percentage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_decreaseBy10Percentage
  (JNIEnv *, jclass);

/*
 * Class:     VolumeController
 * Method:    increaseBy1Percentage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_increaseBy1Percentage
  (JNIEnv *, jclass);

/*
 * Class:     VolumeController
 * Method:    decreaseBy1Percentage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_decreaseBy1Percentage
  (JNIEnv *, jclass);

/*
 * Class:     VolumeController
 * Method:    changeVolume
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_VolumeController_changeVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     VolumeController
 * Method:    getVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_VolumeController_getVolume
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
