/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VolumeController */

#ifndef _Included_VolumeController
#define _Included_VolumeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VolumeController
 * Method:    muteOn
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_VolumeController_muteOn
  (JNIEnv *, jobject);

/*
 * Class:     VolumeController
 * Method:    muteOff
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_VolumeController_muteOff
  (JNIEnv *, jobject);

/*
 * Class:     VolumeController
 * Method:    changeVolume
 * Signature: (F)S
 */
JNIEXPORT jshort JNICALL Java_VolumeController_changeVolume
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
